linters:
  enable-all: true
  disable:  # List any linters here that you explicitly want to disable

issues:
  max-issues-per-linter: 0  # 0 means unlimited
  max-same-issues: 0        

run:
  deadline: 5m
