linters:
  enable:
    - gofmt
    - goimports
    - golint
    - govet
    - errcheck
    - staticcheck
    - unused
    - deadcode
    - structcheck
    - varcheck
    - ineffassign
    - misspell
    - unconvert

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  
run:
  deadline: 5m
