name: GH Action Workflow - Build, Lint, Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-lint-test:
    name: Build, Lint, Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
        args: --timeout 5m

    - name: Run Tests
      run: go test -list 'Test' ./... | grep -v '_NoCI' | xargs -I {} go test -v -run ^{}$

